#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
BASE_DIR="${BASE_DIR:-${PROJECT_DIR}/core}"

TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
EXPERIMENT_ROOT="${EXPERIMENT_ROOT:-${PROJECT_DIR}/outputs/closed_loop}"
RUN_NAME="${RUN_NAME:-round1_rl_collect_${TIMESTAMP}}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-${EXPERIMENT_ROOT}/${RUN_NAME}/rl}"
ROLLOUT_DIR="${ROLLOUT_DIR:-${EXPERIMENT_ROOT}/${RUN_NAME}/rollouts}"
ROLLOUT_LOG_PATH="${ROLLOUT_LOG_PATH:-${ROLLOUT_DIR}/rl_rollouts.jsonl}"

export PROJECT_DIR
export BASE_DIR
export CHECKPOINT_DIR
export REWARD_FN="${REWARD_FN:-${BASE_DIR}/reward_fn_collect.py}"
export ROLLOUT_LOG_PATH
export ROLLOUT_LOG_FORMAT_FAILURES="${ROLLOUT_LOG_FORMAT_FAILURES:-1}"

export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-10}"
export SAVE_FREQ="${SAVE_FREQ:-${TOTAL_TRAINING_STEPS}}"
export TEST_FREQ="${TEST_FREQ:--1}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-1}"
export ROLLOUT_N="${ROLLOUT_N:-8}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-48}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-48}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-48}"
export MAX_ACTOR_CKPT_TO_KEEP="${MAX_ACTOR_CKPT_TO_KEEP:-10}"

mkdir -p "${CHECKPOINT_DIR}" "${ROLLOUT_DIR}"

echo "[INFO] PROJECT_DIR=${PROJECT_DIR}"
echo "[INFO] CHECKPOINT_DIR=${CHECKPOINT_DIR}"
echo "[INFO] ROLLOUT_LOG_PATH=${ROLLOUT_LOG_PATH}"
echo "[INFO] TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS}"

"${PROJECT_DIR}/scripts/train_grpo_base_parallel4.sh" "$@"
